-- =============================================================================
-- ARUNA AI — SUPABASE DATABASE SCHEMA WITH RLS POLICIES
-- =============================================================================
-- Generated by analyzing the full frontend codebase.
-- All tables use UUID primary keys, Row Level Security (RLS) is enabled on every
-- table, and policies follow the principle of least-privilege.
-- Run this file in the Supabase SQL editor (or via supabase db push).
-- =============================================================================


-- ---------------------------------------------------------------------------
-- EXTENSIONS
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ===========================================================================
-- 1. PROFILES
--    One row per auth.users entry. Extended user data lives here.
-- ===========================================================================
CREATE TABLE public.profiles (
  id             UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name      TEXT NOT NULL DEFAULT '',
  email          TEXT NOT NULL,
  avatar_url     TEXT,
  -- Memory preferences (from SettingsPage)
  personal_space_memory   BOOLEAN NOT NULL DEFAULT TRUE,
  professional_space_memory BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Users can read and update only their own profile
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Supabase trigger: auto-create a profile row on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();


-- ===========================================================================
-- 2. WORKSPACES
--    Personal, Professional, or Shared workspaces.
-- ===========================================================================
CREATE TYPE public.workspace_type AS ENUM ('Personal', 'Professional', 'Shared');

CREATE TABLE public.workspaces (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  owner_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  description  TEXT NOT NULL DEFAULT '',
  emoji        TEXT NOT NULL DEFAULT '🗂️',
  type         public.workspace_type NOT NULL DEFAULT 'Personal',
  is_pinned    BOOLEAN NOT NULL DEFAULT FALSE,
  -- Aggregate counters (updated by triggers / functions)
  chat_count   INT NOT NULL DEFAULT 0,
  file_count   INT NOT NULL DEFAULT 0,
  output_count INT NOT NULL DEFAULT 0,
  last_active_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER workspaces_updated_at BEFORE UPDATE ON public.workspaces
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();


-- ===========================================================================
-- 3. WORKSPACE MEMBERS
--    Many-to-many: users ↔ workspaces.
--    Must be created BEFORE is_workspace_member() function below.
-- ===========================================================================
CREATE TYPE public.workspace_role AS ENUM ('owner', 'editor', 'viewer');

CREATE TABLE public.workspace_members (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role         public.workspace_role NOT NULL DEFAULT 'editor',
  joined_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, user_id)
);

ALTER TABLE public.workspace_members ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- Helper: is the current user a member of (or owner of) a workspace?
-- Defined AFTER workspace_members table so the relation exists.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_workspace_member(workspace_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.workspace_members
    WHERE workspace_id = $1 AND user_id = auth.uid()
  ) OR EXISTS (
    SELECT 1 FROM public.workspaces
    WHERE id = $1 AND owner_id = auth.uid()
  );
$$;


-- RLS policies for workspaces (now safe — helper function exists)
CREATE POLICY "workspaces_select" ON public.workspaces
  FOR SELECT USING (public.is_workspace_member(id));

CREATE POLICY "workspaces_insert_owner" ON public.workspaces
  FOR INSERT WITH CHECK (owner_id = auth.uid());

CREATE POLICY "workspaces_update_owner" ON public.workspaces
  FOR UPDATE USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

CREATE POLICY "workspaces_delete_owner" ON public.workspaces
  FOR DELETE USING (owner_id = auth.uid());


-- RLS policies for workspace_members (now safe — helper function exists)
-- Members can see other members of workspaces they belong to
CREATE POLICY "workspace_members_select" ON public.workspace_members
  FOR SELECT USING (public.is_workspace_member(workspace_id));

-- Only workspace owners can add/remove members
CREATE POLICY "workspace_members_insert_owner" ON public.workspace_members
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.workspaces
      WHERE id = workspace_id AND owner_id = auth.uid()
    )
  );

CREATE POLICY "workspace_members_delete_owner" ON public.workspace_members
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.workspaces
      WHERE id = workspace_id AND owner_id = auth.uid()
    )
  );


-- ===========================================================================
-- 4. CHAT SESSIONS
-- ===========================================================================
CREATE TYPE public.chat_mode AS ENUM ('personal', 'professional', 'general');

CREATE TABLE public.chat_sessions (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id      UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  title        TEXT NOT NULL DEFAULT 'New Chat',
  mode         public.chat_mode NOT NULL DEFAULT 'general',
  is_starred   BOOLEAN NOT NULL DEFAULT FALSE,
  is_archived  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER chat_sessions_updated_at BEFORE UPDATE ON public.chat_sessions
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "chat_sessions_select" ON public.chat_sessions
  FOR SELECT USING (
    user_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

CREATE POLICY "chat_sessions_insert" ON public.chat_sessions
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "chat_sessions_update" ON public.chat_sessions
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "chat_sessions_delete" ON public.chat_sessions
  FOR DELETE USING (user_id = auth.uid());


-- ===========================================================================
-- 5. MESSAGES
--    Individual messages within a chat session.
-- ===========================================================================
CREATE TYPE public.message_role AS ENUM ('user', 'assistant', 'system');

CREATE TABLE public.messages (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id     UUID NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
  user_id        UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  role           public.message_role NOT NULL,
  content        TEXT NOT NULL,
  -- AI model used for assistant messages
  model          TEXT,
  -- Cost in smallest currency unit (paise)
  cost_paise     INT NOT NULL DEFAULT 0,
  -- Optional: attached file references (vault file IDs)
  attached_file_ids UUID[] DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Can read messages if you can read the session
CREATE POLICY "messages_select" ON public.messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.chat_sessions cs
      WHERE cs.id = session_id
        AND (cs.user_id = auth.uid()
             OR (cs.workspace_id IS NOT NULL
                 AND public.is_workspace_member(cs.workspace_id)))
    )
  );

CREATE POLICY "messages_insert" ON public.messages
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.chat_sessions cs
      WHERE cs.id = session_id AND cs.user_id = auth.uid()
    )
  );

-- Messages are immutable after creation — no UPDATE or DELETE policies.


-- ===========================================================================
-- 6. TASKS  (Agent Execution Records)
-- ===========================================================================
CREATE TYPE public.task_status AS ENUM ('Running', 'Queued', 'Completed', 'Failed', 'Cancelled');

CREATE TABLE public.tasks (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  workspace_id   UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  session_id     UUID REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  title          TEXT NOT NULL,
  status         public.task_status NOT NULL DEFAULT 'Queued',
  model          TEXT NOT NULL DEFAULT 'gpt-4o',
  -- Cost in paise
  cost_paise     INT NOT NULL DEFAULT 0,
  -- Duration in seconds
  duration_secs  INT,
  progress       SMALLINT NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  started_at     TIMESTAMPTZ,
  completed_at   TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER tasks_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "tasks_select" ON public.tasks
  FOR SELECT USING (
    user_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

CREATE POLICY "tasks_insert" ON public.tasks
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Only the task owner or a service role can update tasks
CREATE POLICY "tasks_update" ON public.tasks
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "tasks_delete" ON public.tasks
  FOR DELETE USING (user_id = auth.uid());


-- ===========================================================================
-- 7. TASK LOGS  (Step-by-step agent execution logs)
-- ===========================================================================
CREATE TYPE public.log_type AS ENUM ('planning', 'executing', 'reasoning', 'complete', 'error');

CREATE TABLE public.task_logs (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  task_id     UUID NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  type        public.log_type NOT NULL,
  description TEXT NOT NULL,
  -- Elapsed seconds since task start
  elapsed_secs INT NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.task_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "task_logs_select" ON public.task_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
  );

CREATE POLICY "task_logs_insert" ON public.task_logs
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
  );


-- ===========================================================================
-- 8. NOTIFICATIONS
-- ===========================================================================
CREATE TYPE public.notification_type AS ENUM ('task', 'approval', 'mention', 'system');

CREATE TABLE public.notifications (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type          public.notification_type NOT NULL,
  title         TEXT NOT NULL,
  description   TEXT NOT NULL DEFAULT '',
  action_label  TEXT,
  action_url    TEXT,
  is_read       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notifications_select_own" ON public.notifications
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "notifications_update_own" ON public.notifications
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "notifications_delete_own" ON public.notifications
  FOR DELETE USING (user_id = auth.uid());

-- Service role (edge functions) can insert notifications for any user
-- No INSERT policy for authenticated role — use service role key from functions.


-- ===========================================================================
-- 9. APPROVALS  (Human-in-the-Loop)
-- ===========================================================================
CREATE TYPE public.approval_status AS ENUM ('Pending', 'Approved', 'Rejected', 'Modified');
CREATE TYPE public.risk_level     AS ENUM ('Low', 'Medium', 'High');

CREATE TABLE public.approvals (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id           UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  workspace_id      UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  task_id           UUID REFERENCES public.tasks(id) ON DELETE SET NULL,
  title             TEXT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  status            public.approval_status NOT NULL DEFAULT 'Pending',
  risk              public.risk_level NOT NULL DEFAULT 'Low',
  goal              TEXT,
  risk_explanation  TEXT,
  -- JSONB payload with action-specific details (recipients, integration, etc.)
  details           JSONB NOT NULL DEFAULT '{}',
  requester         TEXT NOT NULL DEFAULT 'Automated Workflow',
  reviewed_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER approvals_updated_at BEFORE UPDATE ON public.approvals
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "approvals_select" ON public.approvals
  FOR SELECT USING (
    user_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

CREATE POLICY "approvals_insert" ON public.approvals
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Only the owner can approve/reject (update status)
CREATE POLICY "approvals_update" ON public.approvals
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());


-- ===========================================================================
-- 10. VAULT FILES
-- ===========================================================================
CREATE TABLE public.vault_files (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id   UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  uploader_id    UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  -- Storage path inside Supabase Storage bucket "vault"
  storage_path   TEXT NOT NULL UNIQUE,
  mime_type      TEXT NOT NULL DEFAULT 'application/octet-stream',
  size_bytes     BIGINT NOT NULL DEFAULT 0,
  -- Human-friendly type label: pdf, doc, sheet, slide, image, other
  file_type      TEXT NOT NULL DEFAULT 'other',
  is_agent_generated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.vault_files ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER vault_files_updated_at BEFORE UPDATE ON public.vault_files
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "vault_files_select" ON public.vault_files
  FOR SELECT USING (
    uploader_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

CREATE POLICY "vault_files_insert" ON public.vault_files
  FOR INSERT WITH CHECK (uploader_id = auth.uid());

CREATE POLICY "vault_files_update" ON public.vault_files
  FOR UPDATE USING (uploader_id = auth.uid()) WITH CHECK (uploader_id = auth.uid());

CREATE POLICY "vault_files_delete" ON public.vault_files
  FOR DELETE USING (uploader_id = auth.uid());


-- ===========================================================================
-- 11. INTEGRATIONS
--    Tracks which third-party tools each user has connected.
-- ===========================================================================
CREATE TYPE public.integration_status AS ENUM ('connected', 'disconnected', 'error');

CREATE TABLE public.integrations (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Canonical integration identifier: "slack", "google_drive", "gmail", etc.
  provider       TEXT NOT NULL,
  display_name   TEXT NOT NULL,
  status         public.integration_status NOT NULL DEFAULT 'disconnected',
  -- Whether the agent can act on this integration without human approval
  autonomous     BOOLEAN NOT NULL DEFAULT FALSE,
  -- OAuth tokens stored encrypted (use Supabase Vault / pgcrypto in prod)
  access_token   TEXT,
  refresh_token  TEXT,
  token_expires_at TIMESTAMPTZ,
  -- Extra provider-specific config
  metadata       JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, provider)
);

ALTER TABLE public.integrations ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER integrations_updated_at BEFORE UPDATE ON public.integrations
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "integrations_select_own" ON public.integrations
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "integrations_insert_own" ON public.integrations
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "integrations_update_own" ON public.integrations
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY "integrations_delete_own" ON public.integrations
  FOR DELETE USING (user_id = auth.uid());


-- ===========================================================================
-- 12. WORKSPACE MEMORY
--    Key facts the AI remembers about a workspace.
-- ===========================================================================
CREATE TABLE public.workspace_memory (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  -- The user or agent that added this fact
  added_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  fact         TEXT NOT NULL,
  -- Embedding vector for semantic search (requires pgvector extension)
  -- embedding   VECTOR(1536),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.workspace_memory ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER workspace_memory_updated_at BEFORE UPDATE ON public.workspace_memory
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "workspace_memory_select" ON public.workspace_memory
  FOR SELECT USING (public.is_workspace_member(workspace_id));

CREATE POLICY "workspace_memory_insert" ON public.workspace_memory
  FOR INSERT WITH CHECK (public.is_workspace_member(workspace_id));

CREATE POLICY "workspace_memory_update" ON public.workspace_memory
  FOR UPDATE USING (public.is_workspace_member(workspace_id))
  WITH CHECK (public.is_workspace_member(workspace_id));

CREATE POLICY "workspace_memory_delete" ON public.workspace_memory
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.workspaces w
      WHERE w.id = workspace_id AND w.owner_id = auth.uid()
    )
    OR added_by = auth.uid()
  );


-- ===========================================================================
-- 13. ACTIVITY LOGS
--    Append-only audit trail for workspace events.
-- ===========================================================================
CREATE TABLE public.activity_logs (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID REFERENCES public.workspaces(id) ON DELETE CASCADE,
  user_id      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,          -- e.g. "uploaded", "shared", "approved"
  target       TEXT NOT NULL,          -- e.g. "Q3 Report.pdf"
  target_id    UUID,                   -- optional FK to affected row
  target_type  TEXT,                   -- e.g. "vault_file", "approval", "task"
  metadata     JSONB NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "activity_logs_select" ON public.activity_logs
  FOR SELECT USING (
    user_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

-- Inserts happen via service-role edge functions only — no user INSERT policy.


-- ===========================================================================
-- 14. BILLING / USAGE RECORDS
--    One row per chargeable AI call.
-- ===========================================================================
CREATE TABLE public.billing_records (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id        UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  workspace_id   UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  session_id     UUID REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  task_id        UUID REFERENCES public.tasks(id) ON DELETE SET NULL,
  model          TEXT NOT NULL,
  -- Tokens consumed
  input_tokens   INT NOT NULL DEFAULT 0,
  output_tokens  INT NOT NULL DEFAULT 0,
  -- Cost in paise (₹1 = 100 paise)
  cost_paise     INT NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.billing_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "billing_records_select_own" ON public.billing_records
  FOR SELECT USING (user_id = auth.uid());

-- Inserts done by service role (edge functions) only.


-- ===========================================================================
-- 15. RESEARCH RESULTS
-- ===========================================================================
CREATE TABLE public.research_results (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id      UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  workspace_id UUID REFERENCES public.workspaces(id) ON DELETE SET NULL,
  session_id   UUID REFERENCES public.chat_sessions(id) ON DELETE SET NULL,
  query        TEXT NOT NULL,
  summary      TEXT NOT NULL DEFAULT '',
  -- Array of {title, url, snippet, color} objects
  sources      JSONB NOT NULL DEFAULT '[]',
  -- Saved to vault?
  vault_file_id UUID REFERENCES public.vault_files(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.research_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "research_results_select" ON public.research_results
  FOR SELECT USING (
    user_id = auth.uid()
    OR (workspace_id IS NOT NULL AND public.is_workspace_member(workspace_id))
  );

CREATE POLICY "research_results_insert" ON public.research_results
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "research_results_delete" ON public.research_results
  FOR DELETE USING (user_id = auth.uid());


-- ===========================================================================
-- 16. WORKFLOWS
-- ===========================================================================
CREATE TYPE public.workflow_status AS ENUM ('active', 'paused', 'draft', 'archived');

CREATE TABLE public.workflows (
  id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id   UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  created_by     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  description    TEXT NOT NULL DEFAULT '',
  status         public.workflow_status NOT NULL DEFAULT 'draft',
  -- Workflow definition (DAG of steps) stored as JSONB
  definition     JSONB NOT NULL DEFAULT '{}',
  -- Cron schedule (nullable = manual trigger only)
  schedule       TEXT,
  last_run_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.workflows ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER workflows_updated_at BEFORE UPDATE ON public.workflows
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "workflows_select" ON public.workflows
  FOR SELECT USING (public.is_workspace_member(workspace_id));

CREATE POLICY "workflows_insert" ON public.workflows
  FOR INSERT WITH CHECK (
    created_by = auth.uid()
    AND public.is_workspace_member(workspace_id)
  );

CREATE POLICY "workflows_update" ON public.workflows
  FOR UPDATE USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.workspace_members wm
      WHERE wm.workspace_id = workflows.workspace_id
        AND wm.user_id = auth.uid()
        AND wm.role IN ('owner', 'editor')
    )
  );

CREATE POLICY "workflows_delete" ON public.workflows
  FOR DELETE USING (
    created_by = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.workspaces w
      WHERE w.id = workspace_id AND w.owner_id = auth.uid()
    )
  );


-- ===========================================================================
-- 17. CONTACT INQUIRIES  (from the public /contact page)
-- ===========================================================================
CREATE TYPE public.inquiry_type AS ENUM ('general', 'enterprise', 'partnership', 'support');

CREATE TABLE public.contact_inquiries (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  first_name   TEXT NOT NULL,
  last_name    TEXT NOT NULL,
  work_email   TEXT NOT NULL,
  inquiry      public.inquiry_type NOT NULL DEFAULT 'general',
  message      TEXT NOT NULL,
  -- Optional: link to registered user if they were logged in
  user_id      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_resolved  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.contact_inquiries ENABLE ROW LEVEL SECURITY;

-- Public users (anon role) can insert; only service role can read all rows.
CREATE POLICY "contact_inquiries_insert_anon" ON public.contact_inquiries
  FOR INSERT WITH CHECK (TRUE);

-- Logged-in users can see their own submissions
CREATE POLICY "contact_inquiries_select_own" ON public.contact_inquiries
  FOR SELECT USING (user_id = auth.uid());


-- ===========================================================================
-- 18. USER SETTINGS  (model preferences, UI preferences, etc.)
--    One row per user, defaults lazily inserted on first write.
-- ===========================================================================
CREATE TABLE public.user_settings (
  user_id          UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Preferred AI tier: 'faster' | 'balanced' | 'best'
  model_tier       TEXT NOT NULL DEFAULT 'balanced',
  -- Preferred default chat mode
  default_mode     public.chat_mode NOT NULL DEFAULT 'general',
  -- Monthly budget in paise
  monthly_budget_paise BIGINT NOT NULL DEFAULT 150000,
  -- Notification preferences (granular toggles as JSONB)
  notification_prefs JSONB NOT NULL DEFAULT '{"tasks":true,"approvals":true,"mentions":true,"system":true}',
  -- Theme: 'light' | 'dark' | 'system'
  theme            TEXT NOT NULL DEFAULT 'system',
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER user_settings_updated_at BEFORE UPDATE ON public.user_settings
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

CREATE POLICY "user_settings_select_own" ON public.user_settings
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "user_settings_insert_own" ON public.user_settings
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "user_settings_update_own" ON public.user_settings
  FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());


-- ===========================================================================
-- INDEXES  (performance on common query patterns)
-- ===========================================================================
-- Chat sessions
CREATE INDEX idx_chat_sessions_user       ON public.chat_sessions(user_id);
CREATE INDEX idx_chat_sessions_workspace  ON public.chat_sessions(workspace_id);
CREATE INDEX idx_chat_sessions_created    ON public.chat_sessions(created_at DESC);

-- Messages
CREATE INDEX idx_messages_session         ON public.messages(session_id);
CREATE INDEX idx_messages_created         ON public.messages(created_at);

-- Tasks
CREATE INDEX idx_tasks_user              ON public.tasks(user_id);
CREATE INDEX idx_tasks_workspace         ON public.tasks(workspace_id);
CREATE INDEX idx_tasks_status            ON public.tasks(status);
CREATE INDEX idx_tasks_created           ON public.tasks(created_at DESC);

-- Task logs
CREATE INDEX idx_task_logs_task          ON public.task_logs(task_id);

-- Notifications
CREATE INDEX idx_notifications_user      ON public.notifications(user_id);
CREATE INDEX idx_notifications_unread    ON public.notifications(user_id, is_read) WHERE is_read = FALSE;

-- Approvals
CREATE INDEX idx_approvals_user          ON public.approvals(user_id);
CREATE INDEX idx_approvals_workspace     ON public.approvals(workspace_id);
CREATE INDEX idx_approvals_status        ON public.approvals(status);

-- Vault files
CREATE INDEX idx_vault_files_workspace   ON public.vault_files(workspace_id);
CREATE INDEX idx_vault_files_uploader    ON public.vault_files(uploader_id);

-- Activity logs
CREATE INDEX idx_activity_workspace      ON public.activity_logs(workspace_id);
CREATE INDEX idx_activity_created        ON public.activity_logs(created_at DESC);

-- Billing
CREATE INDEX idx_billing_user            ON public.billing_records(user_id);
CREATE INDEX idx_billing_created         ON public.billing_records(created_at DESC);

-- Workspace memory
CREATE INDEX idx_workspace_memory_ws     ON public.workspace_memory(workspace_id);

-- Workflows
CREATE INDEX idx_workflows_workspace     ON public.workflows(workspace_id);


-- ===========================================================================
-- STORAGE BUCKETS (run via Supabase Dashboard or Management API)
-- ===========================================================================
-- bucket: "vault"         — user-uploaded files and agent outputs
--   public: false
--   allowed mime types: * (any)
--   max file size: 50MB
--
-- bucket: "avatars"       — user profile pictures
--   public: true
--   allowed mime types: image/*
--   max file size: 2MB
--
-- Storage RLS for "vault" bucket:
--   SELECT: auth.uid() IS NOT NULL  (authenticated reads only; files checked via vault_files table)
--   INSERT: auth.uid() IS NOT NULL
--   DELETE: owner only (checked via service function)


-- ===========================================================================
-- REALTIME SUBSCRIPTIONS (enable in Supabase Dashboard)
-- ===========================================================================
-- Enable realtime on:
--   • messages           — live chat streaming
--   • tasks              — live task status updates
--   • task_logs          — live agent log streaming
--   • notifications      — push notifications to user
--   • approvals          — live approval queue

ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.task_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.approvals;


-- ===========================================================================
-- HELPER VIEWS
-- ===========================================================================

-- Current user's unread notification count
CREATE OR REPLACE VIEW public.unread_notification_count AS
  SELECT COUNT(*) AS count
  FROM public.notifications
  WHERE user_id = auth.uid() AND is_read = FALSE;

-- This month's billing summary for the current user
CREATE OR REPLACE VIEW public.current_month_usage AS
  SELECT
    SUM(cost_paise)                        AS total_paise,
    SUM(input_tokens + output_tokens)      AS total_tokens,
    COUNT(*)                               AS total_calls,
    model
  FROM public.billing_records
  WHERE user_id = auth.uid()
    AND date_trunc('month', created_at) = date_trunc('month', NOW())
  GROUP BY model;


-- ===========================================================================
-- END OF SCHEMA
-- ===========================================================================
